### ISSUE TITLE
Different counting reactions

### ISSUE THREAD

**Issue by astraesoftware** [HazelnutStudio/Hazelbot#16]
Add different reactions to counting messages depending on context. Like a 💯reaction for every 100th number, or a different checkmark react after the highest count has been overtaken

**Comment by astraesoftware** [comment]
react with 2️⃣ when a number contains only twos

**Comment by dispfr** [comment]
are we doing this for every number
like reacting with 1️⃣ if its only ones
and 3️⃣ if its only threes, etc, etc

**Comment by astraesoftware** [comment]
no i was thinking just with 2 because of the # 2 channel

**Comment by astraesoftware** [comment]
added 😊

**Comment by astraesoftware** [comment]
this hasn't been added to 2.0 yet
