### ISSUE TITLE
Hazelbot sends quote message twice during quote voting

### ISSUE THREAD

**Issue by dispfr** [HazelnutStudio/Hazelbot#8]
pretty much, if a quote is voted for after it has met the vote quota before hazelbot can delete the message to vote for it, the quote sends twice

we talked about this last night

**Comment by astraesoftware** [comment]
i think the best way to handle this would be to handle reaction events synchronously rather than asynchronously, basically involving putting all the reaction events in a list as we receive them, and then sorting through said list one at a time

**Comment by astraesoftware** [comment]
fixed in 2.0
